### ISSUE TITLE
remove pacejs

### ISSUE THREAD

**Issue by acoshift** [acoshift/acourse#107]

**Comment by BioMaRu** [comment]
Can you provide a screenshot on mobile?

**Comment by acoshift** [comment]
น่าจะเอาออกไปเลยดีไหม จะได้โหลดเร็วขึ้นนิดนึงเพราะว่าตอนนี้
- pacejs มันเป็น script ที่ block อยู่ใน head
- ใส่เป็น async [defer] แล้วมันแปลก ๆ ต้อง block ใน head เท่านั้น
- มันทำงานเมื่อ head ถูกส่งมาที่ browser แล้ว แสดงว่า backend มันน่าจะ process เสร็จแล้ว แต่กำลังส่ง data มา

**Comment by BioMaRu** [comment]
อ่า งั้นเอาออก
