### ISSUE TITLE
Share course to social

### ISSUE THREAD

**Issue by acoshift** [acoshift/acourse#4]
In course detail page should have buttons to share to social media (ex. facebook, google+, twitter)
[don't install other script]

**Comment by acoshift** [comment]
@BioMaRu Can you implement this ?

**Comment by BioMaRu** [comment]
Yep, Technically this is possible with a bowl of Ramen.

**Comment by acoshift** [comment]
D:

**Comment by BioMaRu** [comment]
EX
https://www.facebook.com/sharer/sharer.php?u=https%3A//acourse.io/course/golang-for-beginner

**Comment by acoshift** [comment]
yh

**Comment by acoshift** [comment]
😆

**Comment by BioMaRu** [comment]
🙄
